### ISSUE TITLE
what the fuck 

### ISSUE THREAD

**Issue by GentlemanMC** [Spark-Client-Development/Spark-Client#15]
its actually better than konas and abyss combined

**Comment by Bjottt** [comment]
ok and?

**Comment by ZenovJB** [comment]
> its actually better than konas and abyss combined 

nice iq

**Comment by GentlemanMC** [comment]
> > its actually better than konas and abyss combined
> 
> nice iq

u use oyvey skids so dont talk please

**Comment by ZenovJB** [comment]
> > > its actually better than konas and abyss combined
> > 
> > nice iq
> 
> u use oyvey skids so dont talk please

"zenov pls l3ts be frie3nds ""

**Comment by Donczz** [comment]
Ofc it's better than raion skid (Konas) kek

**Comment by master7720** [comment]
> its actually better than konas and abyss combined

better then konas probably not better then abyss
