### ISSUE TITLE
Building issue.

### ISSUE THREAD

**Issue by Righted1** [Spark-Client-Development/Spark-Client#23]
Basically everytime its in the phase "CompileJava", it'll automatically fail due to coding issues.
`> Task :compileJava
Potential refmap conflict. Duplicate refmap name mixins.spark.refmap.json specified for sourceSet main, already defined for sourceSet main
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\manager\CombatManager.java:3: warning: POP is internal proprietary API and may be removed in a future release
import com.sun.org.apache.bcel.internal.generic.POP;
                                               ^
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\util\ReflectionUtil.java:4: warning: FileURLConnection is internal proprietary API and may be removed in a future release
import sun.net.www.protocol.file.FileURLConnection;
                                ^
Note: SpongePowered MIXIN Annotation Processor Version=0.7.11
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: Loading searge mappings from C:\Users\stefa\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_stable\39\1.12.2\srgs\mcp-srg.srg
Note: Loading notch mappings from C:\Users\stefa\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_stable\39\1.12.2\srgs\mcp-notch.srg
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\mixin\mixins\baritone\MixinStateImplementation.java:40: warning: @Inject target requires method signature because enclosing type information for net.minecraft.block.state.BlockStateContainer$StateImplementation is unavailable
    @Inject(
    ^
Note: Writing refmap to C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\tmp\compileJava\compileJava-refmap.json
Note: Writing refmap to C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\tmp\compileJava\compileJava-refmap.json
Note: Writing searge output SRGs to C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\tmp\compileJava\mcp-srg.srg
Note: Writing notch output SRGs to C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\tmp\compileJava\mcp-notch.srg
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\manager\CombatManager.java:3: warning: POP is internal proprietary API and may be removed in a future release
import com.sun.org.apache.bcel.internal.generic.POP;
                                               ^
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\util\ReflectionUtil.java:4: warning: FileURLConnection is internal proprietary API and may be removed in a future release
import sun.net.www.protocol.file.FileURLConnection;
                                ^
Note: Writing refmap to C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\tmp\compileJava\compileJava-refmap.json
Note: Writing refmap to C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\tmp\compileJava\compileJava-refmap.json
Note: Writing searge output SRGs to C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\tmp\compileJava\mcp-srg.srg
Note: Writing notch output SRGs to C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\tmp\compileJava\mcp-notch.srg
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\manager\CombatManager.java:3: warning: POP is internal proprietary API and may be removed in a future release
import com.sun.org.apache.bcel.internal.generic.POP;
                                               ^
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\util\ReflectionUtil.java:4: warning: FileURLConnection is internal proprietary API and may be removed in a future release
import sun.net.www.protocol.file.FileURLConnection;
                                ^
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\systems\module\Module.java:34: error: cannot find symbol
        return this.isEnabled;
                   ^
  symbol: variable isEnabled
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\systems\module\Module.java:94: error: cannot find symbol
        if (!this.isEnabled) {
                 ^
  symbol: variable isEnabled
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\systems\module\Module.java:100: error: cannot find symbol
            this.isEnabled = true;
                ^
  symbol: variable isEnabled
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\systems\module\Module.java:103: error: cannot find symbol
            if (Notifications.INSTANCE.toggle.getValue() && isEnabled && !this.muted) {
                                                            ^
  symbol:   variable isEnabled
  location: class Module
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\systems\module\Module.java:110: error: cannot find symbol
        if (this.isEnabled) {
                ^
  symbol: variable isEnabled
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\systems\module\Module.java:110: error: illegal start of type
        if (this.isEnabled) {
           ^
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\systems\module\Module.java:115: error: cannot find symbol
            this.isEnabled = false;
                ^
  symbol: variable isEnabled
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\systems\module\Module.java:118: error: cannot find symbol
            if (Notifications.INSTANCE.toggle.getValue() && !isEnabled && !this.muted) {
                                                             ^
  symbol:   variable isEnabled
  location: class Module
C:\Users\stefa\OneDrive\Bureau\Spark-Client-master\build\sources\main\java\me\wallhacks\spark\util\ReflectionUtil.java:90: warning: FileURLConnection is internal proprietary API and may be removed in a future release
                    } else if (connection instanceof FileURLConnection) {
                                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors
8 warnings

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 42s
5 actionable tasks: 3 executed, 2 up-to-date`

**Comment by master7720** [comment]
heres a fix dont use spark

**Comment by Bjottt** [comment]
but why? i loving that claient

**Comment by master7720** [comment]
nice spelling

**Comment by Bjottt** [comment]
why

**Comment by wallhacks0** [comment]
this issue should be resolved already sorry for the late response. (I took a break from working on spark)
